name: Prebuild Binaries

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - run: npm ci --ignore-scripts
      - run: npm run prerebuild
      - run: npm run prebuild -- --upload ${{secrets.git_hub_token}}