name: Prebuild Binaries

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - run: npm ci --ignore-scripts
      - run: npm run prerebuild
      - run: npm run prebuild -- --upload ${{secrets.git_hub_token}}
