name: Prebuild Binaries

on:
  #push:
  #  branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install --ignore-scripts
      - run: npm run prerebuild
      - run: npm run prebuild:publish
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install --ignore-scripts
      - run: npm run prerebuild
      - run: npm run prebuild:publish
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install --ignore-scripts
      - run: npm run prerebuild
      - run: npm run prebuild:publish
