name: Test

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - run: npm ci --ignore-scripts
      - run: npm run rebuild
      - name: Test
        #if: matrix.os == 'windows-latest'
        run: npm test -- -H "${{secrets.DB_URL}}" -U "${{secrets.DB_USER}}" -P "${{secrets.DB_PWD}}"
